version: "3.4"
services:
  postgres:
    image: "postgres:latest"

  api:
    depends_on:
      - postgres
    build: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "8080:3000"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    restart: always
