version: "3.4"

services:
    # nginx:
    #     restart: always
    #     build:
    #         context: ./nginx
    #     ports:
    #         - "80:80"

    postgres:
        image:
            postgres
        
    zookeeper:
        image: wurstmeister/zookeeper

    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ADVERTISED_HOST_NAME: kafka
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    
    db_service:
        build:
            context: ./DBConnector
        depends_on:
            - kafka
            - postgres
        links:
            - kafka
            - postgres
        restart: on-failure:5

    worker:
        build:
            context: ./Worker
        depends_on:
            - kafka
        links:
            - kafka
        restart: on-failure:5
    
    input_service:
        build:
            context: ./SendIndex
        depends_on:
            - kafka
        links:
            - kafka
        volumes:
            - /app/node_modules
            - ./SendIndex:/app
        ports:
            - "3000:3000"
    
    poll_all_service:
        build:
            context: ./PollAll
        depends_on:
            - kafka
        links:
            - kafka
        volumes:
            - /app/node_modules
            - ./PollAll:/app
        ports:
            - "3001:3000"