version: "3.4"

services:
    # nginx:
    #     restart: always
    #     build:
    #         context: ./nginx
    #     ports:
    #         - "80:80"

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - "9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ADVERTISED_HOST_NAME: kafka
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    
    worker:
        build:
            context: ./Worker
        depends_on:
            - kafka
        links:
            - kafka
    
    input_service:
        build:
            context: ./SendIndex
        depends_on:
            - worker
        links:
            - worker
        volumes:
            - /app/node_modules
            - ./SendIndex:/app
        ports:
            - "3000:3000"