FROM nginx
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./Microservices_Microfrontends.jpg /usr/share/nginx/assets/Microservices_Microfrontends.jpg
COPY default.conf /etc/nginx/conf.d/default.conf