version: "3.4"
services:
  postgres:
    image: "postgres:latest"

  redis:
    image: "redis:latest"

  api:
    depends_on:
      - postgres
      - redis
    build: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "8080:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    restart: always
